In [1]:
from dotenv import load_dotenv
load_dotenv()
import numpy as np

In [2]:
from src.data.loader import DataLoader
data_loader = DataLoader()

In [3]:
player_hand_stats = data_loader.load_player_hand_stats()
player_hand_stats.shape

(2216200, 128)

In [4]:
player_hand_stats.head()

,id,player,general_stats,preflop_stats,flop_stats,turn_stats,river_stats,hand_id,hand_date,tournament,...,player_position_is_early,player_position_is_middle,player_position_is_late,player_position_is_blind,fold_street,all_in_street,face_covering_bet_street,face_all_in_street,facing_covering_bet_move,facing_all_in_move
0,68015,2,68097,68015,68015,68015,68015,1016186032418193414-100-1528204618,2018-06-05 13:16:58+00:00,504,...,False,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN
1,68016,4646,68098,68016,68016,68016,68016,1016186032418193414-100-1528204618,2018-06-05 13:16:58+00:00,504,...,False,False,True,False,PF,NaN,NaN,NaN,NaN,NaN
2,68013,4644,68095,68013,68013,68013,68013,1016186032418193414-100-1528204618,2018-06-05 13:16:58+00:00,504,...,True,False,False,False,PF,NaN,NaN,NaN,NaN,NaN
3,68012,4643,68094,68012,68012,68012,68012,1016186032418193414-100-1528204618,2018-06-05 13:16:58+00:00,504,...,False,False,False,True,F,NaN,NaN,NaN,NaN,NaN
4,68014,4645,68096,68014,68014,68014,68014,1016186032418193414-100-1528204618,2018-06-05 13:16:58+00:00,504,...,False,True,False,False,PF,NaN,NaN,NaN,NaN,NaN

In [5]:
player_hand_stats.describe()

,id,player,general_stats,preflop_stats,flop_stats,turn_stats,river_stats,tournament,max_players,cnt_players,...,id_general,player_general,hand_history,starting_stack,bounty,amount_won,chips_difference,amount_expected_won,total_bet_amount,player_combo_hand_rank_difference
count,2.216200e+06,2.216200e+06,2.216200e+06,2.216200e+06,2.216200e+06,2.216200e+06,2.216200e+06,2.216200e+06,2.216200e+06,2.216200e+06,...,2.152323e+06,2.152323e+06,2.152323e+06,2.152323e+06,2.152323e+06,2.152323e+06,2.152323e+06,2152323.0,2.152323e+06,590928.000000
mean,1.134901e+06,2.918550e+04,1.112321e+06,1.115223e+06,1.116267e+06,1.118304e+06,1.120148e+06,3.552275e+03,6.414950e+00,6.002720e+00,...,1.113693e+06,2.908358e+04,1.933027e+05,9.362407e+04,1.750785e+00,1.049110e+04,2.155271e+02,0.0,8.903979e+03,3.486516
std,6.614051e+05,2.171751e+04,6.431442e+05,6.454846e+05,6.463190e+05,6.479719e+05,6.494638e+05,1.869292e+03,9.716587e-01,1.064072e+00,...,6.514430e+05,2.179131e+04,1.162605e+05,5.071168e+05,5.184656e+00,1.714081e+05,7.960936e+04,0.0,1.375818e+05,2.664116
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,-2.709410e+07,0.0,0.000000e+00,0.000000
25%,5.540828e+05,9.113000e+03,5.540758e+05,5.540758e+05,5.540758e+05,5.540748e+05,5.540748e+05,1.758000e+03,6.000000e+00,6.000000e+00,...,5.386735e+05,8.960000e+03,8.730200e+04,1.665300e+04,0.000000e+00,0.000000e+00,-7.800000e+02,0.0,0.000000e+00,1.000000
50%,1.136640e+06,2.848400e+04,1.112672e+06,1.115784e+06,1.116966e+06,1.119088e+06,1.121016e+06,3.869000e+03,6.000000e+00,6.000000e+00,...,1.116541e+06,2.811900e+04,1.948450e+05,2.554200e+04,0.000000e+00,0.000000e+00,-1.400000e+02,0.0,0.000000e+00,3.000000
75%,1.713941e+06,4.748000e+04,1.670270e+06,1.675878e+06,1.677879e+06,1.681833e+06,1.685404e+06,5.223000e+03,6.000000e+00,6.000000e+00,...,1.686240e+06,4.747800e+04,2.961960e+05,5.875000e+04,2.250000e+00,0.000000e+00,-2.500000e+01,0.0,8.660000e+02,5.000000
max,2.267991e+06,7.053300e+04,2.224320e+06,2.229928e+06,2.231929e+06,2.235883e+06,2.239454e+06,6.842000e+03,1.000000e+01,1.000000e+01,...,2.224320e+06,7.053300e+04,3.909550e+05,8.115331e+07,2.756500e+02,7.939331e+07,2.825410e+07,0.0,5.099921e+07,11.000000

In [6]:
player_hand_stats.select_dtypes(include=["object"]).describe()

,hand_id,hero_combo_short_name,hero_combo_hand,hero_combo_hand_is_suited,hero_combo_hand_is_offsuit,hero_combo_hand_is_paired,hero_combo_hand_is_connector,hero_combo_hand_is_one_gapper,hero_combo_hand_is_two_gapper,hero_combo_hand_is_broadway,...,player_position_is_early,player_position_is_middle,player_position_is_late,player_position_is_blind,fold_street,all_in_street,face_covering_bet_street,face_all_in_street,facing_covering_bet_move,facing_all_in_move
count,2216200,2214589,2214589,2214589,2214589,2214589,2214589,2214589,2214589,2214589,...,2152323,2152323,2152323,2152323,1641132,189081,258325,0,258325,0
unique,383155,1326,169,2,2,2,2,2,2,2,...,2,2,2,2,4,4,4,0,4,0
top,2798446681136300034-113-1683546188,8s2h,52o,False,True,False,False,False,False,False,...,False,False,False,False,PF,PF,PF,NaN,R,NaN
freq,13,2009,20746,1692725,1561444,2083308,1865311,1893878,1921638,1897874,...,1857153,1758535,1434771,1406510,1449250,132661,195237,NaN,119505,NaN