In [1]:
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
from src.data.loader import DataLoader
data_loader = DataLoader()

In [3]:
preflop_player_hand_stats = data_loader.load_preflop_player_hand_stats()
preflop_player_hand_stats.head()

      id symbol
0      1      F
1      2      C
2      3      R
3      4     CF
4      5     RC
..   ...    ...
157  158   RXBB
158  159   RRCC
159  160   BRRR
160  161  RRRRC
161  162    BCR

[162 rows x 2 columns]

,id,player,hand_history,flag_vpip,flag_open_opportunity,flag_open,flag_first_raise,flag_fold,flag_limp,flag_cold_called,...,ratio_to_call_facing_4bet,ratio_first_raise_made,ratio_second_raise_made,total_bet_amount,move_facing_2bet,move_facing_3bet,move_facing_4bet,move_facing_squeeze,move_facing_steal_attempt,actions_sequence
0,49,2,2474,True,False,True,False,False,True,False,...,0.0,0.00000,0.0,150.0,NaN,NaN,NaN,NaN,NaN,C
1,50,163,2474,False,False,False,False,True,False,False,...,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,F
2,5,166,2466,False,False,False,False,True,False,False,...,0.0,0.00000,0.0,0.0,F,NaN,NaN,NaN,F,F
3,6,167,2466,True,False,True,False,False,False,True,...,0.0,0.00000,0.0,200.0,C,NaN,NaN,NaN,C,C
4,1589400,47579,279464,True,False,False,False,False,False,False,...,0.0,0.53333,0.0,2800.0,R,NaN,NaN,NaN,NaN,R

In [4]:
preflop_player_hand_stats.shape

(2229903, 53)

In [5]:
preflop_player_hand_stats.describe()

,id,player,hand_history,count_player_raises,count_player_calls,count_faced_limps,amount_effective_stack,amount_to_call_facing_1bet,amount_to_call_facing_2bet,amount_to_call_facing_3bet,amount_to_call_facing_4bet,amount_first_raise_made,amount_second_raise_made,ratio_to_call_facing_1bet,ratio_to_call_facing_2bet,ratio_to_call_facing_3bet,ratio_to_call_facing_4bet,ratio_first_raise_made,ratio_second_raise_made,total_bet_amount
count,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06,2.229903e+06
mean,1.114974e+06,2.920143e+04,1.931350e+05,1.653045e-01,1.731470e-01,3.842320e-03,6.717064e+04,1.647667e+03,5.152015e+03,1.973710e+03,1.964102e+02,4.992747e+03,2.135782e+02,1.870129e-01,1.486275e-01,3.076632e-02,2.406347e-03,9.551728e-02,2.154276e-03,6.420016e+03
std,6.437218e+05,2.170506e+04,1.144758e+05,3.809722e-01,4.176100e-01,7.863090e-02,3.272717e+05,1.248726e+04,7.919593e+04,4.811926e+04,1.044506e+04,1.186769e+05,1.549391e+04,2.008517e-01,2.293505e-01,1.297656e-01,3.573357e-02,2.262238e-01,3.747041e-02,1.261925e+05
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.575015e+05,9.134000e+03,9.049600e+04,0.000000e+00,0.000000e+00,0.000000e+00,1.168800e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.114977e+06,2.854800e+04,1.943400e+05,0.000000e+00,0.000000e+00,0.000000e+00,2.048000e+04,1.000000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.344100e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.672452e+06,4.748000e+04,2.929580e+05,0.000000e+00,0.000000e+00,0.000000e+00,4.291400e+04,7.000000e+02,7.500000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.316500e-01,2.926800e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.300000e+02
max,2.229928e+06,7.053300e+04,3.909550e+05,3.000000e+00,4.000000e+00,5.000000e+00,3.333233e+07,1.400000e+06,2.767233e+07,2.254309e+07,5.437634e+06,5.099921e+07,9.966278e+06,1.875000e+00,9.949200e-01,9.868300e-01,9.578700e-01,9.975100e-01,9.674900e-01,5.099921e+07

In [6]:
preflop_player_hand_stats.select_dtypes(include="object").describe()

,move_facing_2bet,move_facing_3bet,move_facing_4bet,move_facing_squeeze,move_facing_steal_attempt,actions_sequence
count,852702,154638,17074,14310,269065,2183009
unique,5,5,3,4,5,54
top,F,F,F,F,F,F
freq,586109,106692,8751,8272,173162,1448090